#!/bin/bash
[ ! -d ~/.cache/ear ] && mkdir /home/shadow/.cache/ear
[ ! -f ~/.cache/ear/anc ] && touch /home/shadow/.cache/ear/anc
STATUS=`cat /home/shadow/.cache/ear/anc`
if [[ $STATUS == 0 ]];then
	/home/shadow/.config/swaync/scripts/ear.py anc
	echo "1" > ~/.cache/ear/anc
elif [[ $STATUS == 1 ]];then
	/home/shadow/.config/swaync/scripts/ear.py off
	echo "0" > ~/.cache/ear/anc
else
	echo "0" > ~/.cache/ear/anc 
fi
