#!/bin/bash
[ ! -d ~/.cache/ear ] && mkdir /home/shadow/.cache/ear
[ ! -f ~/.cache/ear/anc ] && touch /home/shadow/.cache/ear/tra
STATUS=`cat /home/shadow/.cache/ear/tra`
if [[ $STATUS == 0 ]];then
	/home/shadow/.config/swaync/scripts/ear.py tra
	echo "1" > ~/.cache/ear/tra
elif [[ $STATUS == 1 ]];then
	/home/shadow/.config/swaync/scripts/ear.py off
	echo "0" > ~/.cache/ear/tra
else 
	echo "0" > ~/.cache/ear/tra 
fi
