#!/bin/bash
album_art=$(playerctl metadata | grep artUrl | awk '{ print $3 }') # changed script
hyprctl notify 3 5000 "rgb(EF5350)" "Failed to Install"
if [[ -z $album_art ]] 
then
   # spotify is dead, we should die to.
   exit
fi
curl -s  "${album_art}" --output "/tmp/cover.jpeg" 
echo "/tmp/cover.jpeg"
