pragma Singleton
import Quickshell
import QtQuick

Singleton {
  readonly property color background: "#1a1111"
  readonly property color error: "#ffb4ab"
  readonly property color error_container: "#93000a"
  readonly property color inverse_on_surface: "#382e2d"
  readonly property color inverse_primary: "#904a47"
  readonly property color inverse_surface: "#f1dedd"
  readonly property color on_background: "#f1dedd"
  readonly property color on_error: "#690005"
  readonly property color on_error_container: "#ffdad6"
  readonly property color on_primary: "#571d1c"
  readonly property color on_primary_container: "#ffdad7"
  readonly property color on_primary_fixed: "#3b080a"
  readonly property color on_primary_fixed_variant: "#733331"
  readonly property color on_secondary: "#442928"
  readonly property color on_secondary_container: "#ffdad7"
  readonly property color on_secondary_fixed: "#2c1514"
  readonly property color on_secondary_fixed_variant: "#5d3f3d"
  readonly property color on_surface: "#f1dedd"
  readonly property color on_surface_variant: "#d8c2c0"
  readonly property color on_tertiary: "#402d05"
  readonly property color on_tertiary_container: "#ffdea8"
  readonly property color on_tertiary_fixed: "#271900"
  readonly property color on_tertiary_fixed_variant: "#594319"
  readonly property color outline: "#a08c8b"
  readonly property color outline_variant: "#534342"
  readonly property color primary: "#ffb3ae"
  readonly property color primary_container: "#733331"
  readonly property color primary_fixed: "#ffdad7"
  readonly property color primary_fixed_dim: "#ffb3ae"
  readonly property color scrim: "#000000"
  readonly property color secondary: "#e7bdba"
  readonly property color secondary_container: "#5d3f3d"
  readonly property color secondary_fixed: "#ffdad7"
  readonly property color secondary_fixed_dim: "#e7bdba"
  readonly property color shadow: "#000000"
  readonly property color surface: "#1a1111"
  readonly property color surface_bright: "#423736"
  readonly property color surface_container: "#271d1d"
  readonly property color surface_container_high: "#322827"
  readonly property color surface_container_highest: "#3d3231"
  readonly property color surface_container_low: "#231919"
  readonly property color surface_container_lowest: "#140c0c"
  readonly property color surface_dim: "#1a1111"
  readonly property color surface_tint: "#ffb3ae"

  readonly property color surface_variant: "#534342"
  readonly property color tertiary: "#e2c28c"
  readonly property color tertiary_container: "#594319"
  readonly property color tertiary_fixed: "#ffdea8"
  readonly property color tertiary_fixed_dim: "#e2c28c"

  function withAlpha(color: color, alpha: real): color {
    return Qt.rgba(color.r, color.g, color.b, alpha)
  }
}
