pragma Singleton
import Quickshell
import QtQuick

Singleton {
  readonly property color background: "#1a1110"
  readonly property color error: "#ffb4ab"
  readonly property color error_container: "#93000a"
  readonly property color inverse_on_surface: "#392e2d"
  readonly property color inverse_primary: "#904a45"
  readonly property color inverse_surface: "#f1dedc"
  readonly property color on_background: "#f1dedc"
  readonly property color on_error: "#690005"
  readonly property color on_error_container: "#ffdad6"
  readonly property color on_primary: "#571e1b"
  readonly property color on_primary_container: "#ffdad6"
  readonly property color on_primary_fixed: "#3b0908"
  readonly property color on_primary_fixed_variant: "#73332f"
  readonly property color on_secondary: "#442927"
  readonly property color on_secondary_container: "#ffdad6"
  readonly property color on_secondary_fixed: "#2c1513"
  readonly property color on_secondary_fixed_variant: "#5d3f3d"
  readonly property color on_surface: "#f1dedc"
  readonly property color on_surface_variant: "#d8c2bf"
  readonly property color on_tertiary: "#402d04"
  readonly property color on_tertiary_container: "#ffdea6"
  readonly property color on_tertiary_fixed: "#261900"
  readonly property color on_tertiary_fixed_variant: "#584419"
  readonly property color outline: "#a08c8a"
  readonly property color outline_variant: "#534342"
  readonly property color primary: "#ffb3ad"
  readonly property color primary_container: "#73332f"
  readonly property color primary_fixed: "#ffdad6"
  readonly property color primary_fixed_dim: "#ffb3ad"
  readonly property color scrim: "#000000"
  readonly property color secondary: "#e7bdb9"
  readonly property color secondary_container: "#5d3f3d"
  readonly property color secondary_fixed: "#ffdad6"
  readonly property color secondary_fixed_dim: "#e7bdb9"
  readonly property color shadow: "#000000"
  readonly property color surface: "#1a1110"
  readonly property color surface_bright: "#423735"
  readonly property color surface_container: "#271d1c"
  readonly property color surface_container_high: "#322827"
  readonly property color surface_container_highest: "#3d3231"
  readonly property color surface_container_low: "#231918"
  readonly property color surface_container_lowest: "#140c0b"
  readonly property color surface_dim: "#1a1110"
  readonly property color surface_tint: "#ffb3ad"

  readonly property color surface_variant: "#534342"
  readonly property color tertiary: "#e1c28c"
  readonly property color tertiary_container: "#584419"
  readonly property color tertiary_fixed: "#ffdea6"
  readonly property color tertiary_fixed_dim: "#e1c28c"

  function withAlpha(color: color, alpha: real): color {
    return Qt.rgba(color.r, color.g, color.b, alpha)
  }
}
