#!/bin/bash

cd ~

# Log WLR errors and logs to the hyprland log. Recommended
export HYPRLAND_LOG_WLR=1
export _JAVA_AWT_WM_NONREPARENTING=1

# Set a cursor size
export XCURSOR_SIZE=24
expr WLR_NO_HARDWARE_CURSORS=1
exec Hyprland

