#!/bin/bash
FILE2="$HOME/.config/mako/config"
frame=$(cat ~/.cache/wal/colors.json | jq -r '.colors.color3')

mako(){

	# bg
	#sed -i -e "s/background-color=#.*/background-color=$background/g" $FILE2 
	sed -i -e "7s/border-color=#.*/border-color=$frame/g" $FILE2 
	sed -i -e "27s/border-color=#.*/border-color=$frame/g" $FILE2 
}
mako
