#!/usr/bin/env sh
HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')
if [ "$HYPRGAMEMODE" = 1 ] ; then
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:drop_shadow 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
	#keyword monitor HDMI-A-1, 1920x1080@59.93900,auto,1,transform,1,bitdepth,10;\
	#keyword monitor HDMI-A-1,disable;\
        keyword decoration:rounding 0"
    swww kill
    brightnessctl set 80%
    notify-send "GameMode ON !"
    pkexec sudo perfmode -fan turbo && sudo perfmode -thermal overboost
    exit
else
	swww init
	notify-send "GameMode OFF !"
	brightnessctl set 10%
	pkexec sudo perfmode -fan balanced && sudo perfmode -thermal silent
	hyprctl reload

fi
