#!/bin/bash
MON1=$(hyprctl monitors -j | jq '.[1].name' | tr -d '\"')
if [ "$MON1" = "HDMI-A-1" ] ; then
    hyprctl --batch "\
	keyword monitor HDMI-A-1,disable"
    exit
fi
hyprctl reload
hyprctl dispatch workspace 2
