#!/bin/bash
STATUS=$(hyprctl activewindow -j | jq '.floating')
RUNNING=$(hyprctl activewindow -j | jq '.initialTitle' | tr -d "\"")

case $RUNNING in
	"Mozilla Firefox")
		if [[ $STATUS == 'false' ]];then
			hyprctl --batch "dispatch togglefloating; \
				dispatch resizeactive exact 752 882; \
				dispatch centerwindow"
		elif [[ $STATUS == 'true' ]];then
			hyprctl --batch "dispatch togglefloating"
		fi
		;;
	*"mpv")
		if [[ $STATUS == 'false' ]];then
			hyprctl --batch "dispatch togglefloating; \
				dispatch resizeactive exact 732 412; \
				dispatch centerwindow"
		elif [[ $STATUS == 'true' ]];then
			hyprctl --batch "dispatch togglefloating"
		fi
		;;
	"qBittorrent v4.6.4")
		if [[ $STATUS == 'false' ]];then
			hyprctl --batch "dispatch togglefloating; \
				dispatch resizeactive exact 962 785; \
				dispatch centerwindow"
		elif [[ $STATUS == 'true' ]];then
			hyprctl --batch "dispatch togglefloating"
		fi
		;;
	"foot")
		if [[ $STATUS == 'false' ]];then
			hyprctl --batch "dispatch togglefloating; \
				dispatch resizeactive exact 700 500; \
				dispatch centerwindow"
		elif [[ $STATUS == 'true' ]];then
			hyprctl --batch "dispatch togglefloating"
		fi
		;;
	"Spotify"*)
		if [[ $STATUS == 'false' ]];then
			hyprctl --batch "dispatch togglefloating; \
				dispatch resizeactive exact 800 1000; \
				dispatch centerwindow"
		elif [[ $STATUS == 'true' ]];then
			hyprctl --batch "dispatch togglefloating"
		fi
		;;
	"Picture-in-Picture")
		if [[ $STATUS == 'false' ]];then
			hyprctl --batch "dispatch togglefloating; \
				dispatch resizeactive exact 579 327; \
				dispatch centerwindow"
		elif [[ $STATUS == 'true' ]];then
			hyprctl --batch "dispatch togglefloating"
		fi
		;;
	*)
		hyprctl --batch "dispatch togglefloating; \
			dispatch centerwindow"
		;;
esac
