[pyprland]
plugins = [
  "scratchpads"
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false


[scratchpads.ncmpcpp]
animation = "fromTop"
command = "foot --title \"ncmpcpp\" sh -c ncmpcpp"
class = "ncmpcpp"
lazy = true
size = "75% 40%"
