backend = "wal"
color_space = "lab"
palette = "dark"
saturation = 35

[templates]

hypr.template = 'colors-hypr.conf'
hypr.target = '~/.config/hypr/wall.conf'

rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/config/wall.rasi'

swaync.template = 'colors-swaync.css'
swaync.target = '~/.config/swaync/wall.css'

waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/wall.css'

foot.template = 'colors-foot.ini'
foot.target = '~/.config/foot/wall.ini'

firefox.template = 'colors-firefox.json'
firefox.target = '~/.cache/wal/colors.json'

telegram.template = 'colors-telegram.sh'
telegram.target = '~/.cache/wal/colors.sh'

cava.template = 'colors-cava'
cava.target = '~/.config/cava/hyprwinwrap.conf'

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/colors.conf'
