backend = "wal"
color_space = "lab"
palette = "dark"

[templates]

hypr.template = 'templates/colors-hypr.conf'
hypr.target = '~/.config/hypr/wall.conf'

rofi.template = 'templates/colors-rofi.rasi'
rofi.target = '~/.config/rofi/config/wall.rasi'

swaync.template = 'templates/colors-swaync.css'
swaync.target = '~/.config/swaync/wall.css'

waybar.template = 'templates/colors-waybar.css'
waybar.target = '~/.config/waybar/wall.css'

foot.template = 'templates/colors-foot.ini'
foot.target = '~/.config/foot/wall.ini'

firefox.template = 'templates/colors-firefox.json'
firefox.target = '~/.cache/wal/colors.json'

telegram.template = 'templates/colors-telegram.sh'
telegram.target = '~/.cache/wal/colors.sh'

cava.template = 'templates/colors-cava'
cava.target = '~/.config/cava/hyprwinwrap.conf'
